/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moviemanagementsystem.ai;

import com.mycompany.moviemanagementsystem.ui.SearchPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author haicd
 */
public class MainAdminInterface extends javax.swing.JFrame {

    private MovieManagePanel moviePanel;
    private UserManagePanel userPanel;
    public MainAdminInterface() {
        initComponents();
        setLocationRelativeTo(null);
        AdminJDialog dialogAdmin = new AdminJDialog(this, true);
        dialogAdmin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        userBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        movieBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        history = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        exitBtn = new javax.swing.JButton();
        tblMainBoard = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        userBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/10207-man-student-light-skin-tone-icon-24.png"))); // NOI18N
        userBtn.setText("User Account");
        userBtn.setFocusable(false);
        userBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(userBtn);
        jToolBar1.add(jSeparator1);

        movieBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/watch-movie.png"))); // NOI18N
        movieBtn.setText("Manage Movie");
        movieBtn.setFocusable(false);
        movieBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        movieBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        movieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(movieBtn);
        jToolBar1.add(jSeparator2);

        history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/history-book.png"))); // NOI18N
        history.setText("History");
        history.setFocusable(false);
        history.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        history.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        jToolBar1.add(history);
        jToolBar1.add(jSeparator3);

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log-out.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setFocusable(false);
        exitBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(exitBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tblMainBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getUsername(){
        String value=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/ktpm3";
            String userName = "root";
            String password = "";
            Connection connn =DriverManager.getConnection(url, userName, password);
            String sql ="SELECT Username FROM Temp LIMIT 1";
            PreparedStatement pstmt = connn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next()){
                value = rs.getString("Username");
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            e.printStackTrace();
        }
        return value;
    }
    private void movieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieBtnActionPerformed
        if(moviePanel == null){
            moviePanel = new MovieManagePanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/com/mycompany/moviemanagementsystem/icon/open-file-icon-16.png"));
            tblMainBoard.addTab("Search", icon, moviePanel, "Search");}
        tblMainBoard.setSelectedComponent(moviePanel);
    }//GEN-LAST:event_movieBtnActionPerformed

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        if(userPanel == null){
            userPanel = new UserManagePanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/com/mycompany/moviemanagementsystem/icon/open-file-icon-16.png"));
            tblMainBoard.addTab("Search", icon, userPanel, "Search");
        }
        tblMainBoard.setSelectedComponent(userPanel);
    }//GEN-LAST:event_userBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
            int response = JOptionPane.showConfirmDialog(rootPane,"Do you really want to exit ?");
    if(response == JOptionPane.YES_OPTION){
        System.exit(0);
    }
    if(response == JOptionPane.NO_OPTION ){
        System.out.println("Ok");
    }
    if(response == JOptionPane.CANCEL_OPTION){
        System.out.println("Abort exit");
    }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        String id = getUsername(); 
        ActionHistory act = new ActionHistory();
        act.Action(id);
        act.setVisible(true);
        act.setDefaultCloseOperation(act.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_historyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton history;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton movieBtn;
    private javax.swing.JTabbedPane tblMainBoard;
    private javax.swing.JButton userBtn;
    // End of variables declaration//GEN-END:variables
}
