/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.moviemanagementsystem.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.management.Query.value;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author haicd
 */
public class AccountPanel extends javax.swing.JPanel {

    //private ChangeInfo.uusername username;

    /**
     * Creates new form AccountPanel
     */

    
    public AccountPanel() {
        initComponents();
        loadInformation2();
        txtname.setEditable(false);
        txtusername.setEditable(false);
        txtphone.setEditable(false);
        txtpassword.setEditable(false);
    }

    private String getUsername(){
        String value=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/ktpm3";
            String userName = "root";
            String password = "";
            Connection connn =DriverManager.getConnection(url, userName, password);
            String sql ="SELECT Username FROM Temp LIMIT 1";
            PreparedStatement pstmt = connn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next()){
                value = rs.getString("Username");
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            e.printStackTrace();
        }
        return value;
    }
    public void loadInformation2(){
        String getUsername;
          try {
             
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/ktpm3";
            String userName = "root";
            String password = "";
            Connection connn =DriverManager.getConnection(url, userName, password);
            String valueusername =getUsername();
            String sql ="SELECT * FROM users WHERE Username = '"+valueusername+"'";
            PreparedStatement pstmt = connn.prepareStatement(sql);
            //String Name;
            //pstmt.setString(1, Name);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()){
                txtname.setText(rs.getString("Name"));
                txtusername.setText(rs.getString("Username"));
                txtpassword.setText(rs.getString("password"));
                txtphone.setText(rs.getString("Phone"));
                //txtMovieName.setText(getValueAt(row,1).toString());
            }
            rs.close();
            pstmt.close();
            connn.close();
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changebutton = new javax.swing.JButton();
        label1 = new java.awt.Label();
        refreshBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtphone = new java.awt.TextField();
        txtpassword = new java.awt.TextField();
        txtusername = new java.awt.TextField();
        txtname = new java.awt.TextField();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changebutton.setText("Change Password");
        changebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebuttonActionPerformed(evt);
            }
        });
        add(changebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setText("Your information");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 103, -1));

        jLabel4.setText("Phone Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 96, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 126, 86, -1));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 83, 72, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 112, 117, 11));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 71, 117, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 110, 10));

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 63, -1));
        add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 172, 114, -1));

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 122, 114, -1));

        txtusername.setText("\n");
        add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 79, 112, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 41, 112, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white-background-with-blue-tech-hexagon_1017-19366.jpg"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void changebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebuttonActionPerformed
       
       ChangeInfoUserFrame adu = new ChangeInfoUserFrame();
       
       adu.setVisible(true);
       adu.setDefaultCloseOperation(adu.DISPOSE_ON_CLOSE);
       
       
    }//GEN-LAST:event_changebuttonActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadInformation2();
    }//GEN-LAST:event_refreshBtnActionPerformed
/*private void loadUsersDetail(){
    try{
    } catch (Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
    e.printStackTrace();
}
}*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private java.awt.Label label1;
    private javax.swing.JButton refreshBtn;
    private java.awt.TextField txtname;
    private java.awt.TextField txtpassword;
    private java.awt.TextField txtphone;
    private java.awt.TextField txtusername;
    // End of variables declaration//GEN-END:variables
}
