/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.moviemanagementsystem.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author haicd
 */
public class ExplorePanel extends javax.swing.JPanel {
    String url = "jdbc:mysql://localhost/ktpm3";
    String userName = "root";
    String password = "";
    int row;
    /**
     * Creates new form ExplorePanel
     */
    public ExplorePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        exploreTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        viewButtonExploringPanel = new javax.swing.JButton();
        shuffleButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(375, 455));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 117, 351, 10));

        exploreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Movie ", "Genre"
            }
        ));
        jScrollPane1.setViewportView(exploreTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 134, 351, 53));

        jLabel1.setText("Exploring movies and tv series");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 27, -1, -1));

        viewButtonExploringPanel.setText("View");
        viewButtonExploringPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonExploringPanelActionPerformed(evt);
            }
        });
        add(viewButtonExploringPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 61, 125, -1));

        shuffleButton.setText("Explore");
        shuffleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuffleButtonActionPerformed(evt);
            }
        });
        add(shuffleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 61, 125, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 33, 127, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white-background-with-blue-tech-hexagon_1017-19366.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 320));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void shuffleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuffleButtonActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connect =DriverManager.getConnection(url, userName, password);
            String searchQuery = "SELECT Name, Type FROM movies ORDER BY RAND() LIMIT 1;";
            PreparedStatement pst = connect.prepareStatement(searchQuery);
            ResultSet rsSearch = pst.executeQuery();
            exploreTable.setModel(DbUtils.resultSetToTableModel(rsSearch));
            
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_shuffleButtonActionPerformed

    private void viewButtonExploringPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonExploringPanelActionPerformed
        row = exploreTable.getSelectedRow();
        String id = (exploreTable.getModel().getValueAt(row,0).toString());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection connected =DriverManager.getConnection(url, userName, password);
            String sql = "UPDATE movies SET Views = Views + 1 WHERE Name = '"+id+"'";
            PreparedStatement pstmt = connected.prepareStatement(sql);
            pstmt.executeUpdate();
            pstmt.close();
           
        } catch (Exception e){
            e.printStackTrace();
        }
        MovieInformationFrame du = new MovieInformationFrame(id);
        du.loadInformation(id);
        du.setVisible(true);
        du.setDefaultCloseOperation(du.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_viewButtonExploringPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable exploreTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton shuffleButton;
    private javax.swing.JButton viewButtonExploringPanel;
    // End of variables declaration//GEN-END:variables
}
