/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.moviemanagementsystem.ui;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


public class GenrePanel extends javax.swing.JPanel {
    int row;
    JPanel frame1;
    String ids;
    String Name;
    String Type;
    String Description;
    String from;
    
    public GenrePanel() {
        initComponents();
        initComboBox();
    }
    
   public void initComboBox(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/ktpm3";
            String userName = "root";
            String password = "";
            Connection connn =DriverManager.getConnection(url, userName, password);
            String sql = "SELECT COUNT(*) AS `Rows`, `Type` FROM `movies` GROUP BY `Type` ORDER BY `Type`";
            
            PreparedStatement st = connn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                genreBoxGenrePanel.addItem(rs.getString("Type"));
                //v.add(genreBoxGenrePanel);
            }
           
            st.close();
            rs.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            e.printStackTrace();
        }
    }
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated bythe Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        genreBoxGenrePanel = new javax.swing.JComboBox<>();
        viewButton = new javax.swing.JButton();
        tpl2GenreTable = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableName = new javax.swing.JTable();
        OKButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genreBoxGenrePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreBoxGenrePanelActionPerformed(evt);
            }
        });
        add(genreBoxGenrePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, 131, -1));

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 23, 65, -1));

        tableName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Movie Name"
            }
        ));
        jScrollPane1.setViewportView(tableName);

        tpl2GenreTable.addTab("Movie List", jScrollPane1);

        add(tpl2GenreTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 55, -1, 366));

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        add(OKButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 23, 71, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white-background-with-blue-tech-hexagon_1017-19366.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void genreBoxGenrePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreBoxGenrePanelActionPerformed
       
    }//GEN-LAST:event_genreBoxGenrePanelActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
             from = (String) genreBoxGenrePanel.getSelectedItem();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        String url = "jdbc:mysql://localhost/ktpm3";
        String userName = "root";
        String password = "";
        Connection connn =DriverManager.getConnection(url, userName, password);
        String sql = "SELECT Name FROM movies WHERE Type ='"+ from +"'";
        PreparedStatement pstmt = connn.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        String name1 ="";
        int i = 0;
        tableName.setModel(DbUtils.resultSetToTableModel(rs));
        while (rs.next()){
            name1=rs.getString("Name");
        }
        }catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
                }
        //frame1.setVisible(true);
    }//GEN-LAST:event_OKButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        row = tableName.getSelectedRow();
        String id = (tableName.getModel().getValueAt(row,0).toString());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/ktpm3";
            String userName = "root";
            String password = "";
            Connection connected =DriverManager.getConnection(url, userName, password);
            String sql = "UPDATE movies SET Views = Views + 1 WHERE Name = '"+id+"'";
            PreparedStatement pstmt = connected.prepareStatement(sql);
            pstmt.executeUpdate();
            pstmt.close();
           
        } catch (Exception e){
            e.printStackTrace();
        }
        MovieInformationFrame du = new MovieInformationFrame(id);
        du.loadInformation(id);
        du.setVisible(true);
        du.setDefaultCloseOperation(du.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_viewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JComboBox<String> genreBoxGenrePanel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableName;
    private javax.swing.JTabbedPane tpl2GenreTable;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
