/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.moviemanagementsystem.ui;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;


public class MainUserInterface extends javax.swing.JFrame {
    private ExplorePanel mExplorePanel;
    private SearchPanel mSearchPanel;
    private AccountPanel mAccountPanel;
    private GenrePanel mGenrePanel;
    
    /**
     * Creates new form MainForm
     */
    public MainUserInterface() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        exploreButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        searchButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        genresButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        accountButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        tplMainBoard = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorderPainted(false);
        jToolBar1.setEnabled(false);
        jToolBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        exploreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/open-file-icon-16.png"))); // NOI18N
        exploreButton.setText("Explore");
        exploreButton.setFocusable(false);
        exploreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exploreButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exploreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exploreButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(exploreButton);
        jToolBar1.add(jSeparator1);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/search-icon-24.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.setFocusable(false);
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(searchButton);
        jToolBar1.add(jSeparator2);

        genresButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/trendy.png"))); // NOI18N
        genresButton.setText("Genres");
        genresButton.setFocusable(false);
        genresButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        genresButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        genresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genresButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(genresButton);
        jToolBar1.add(jSeparator3);

        accountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/Person-Male-Light-icon-24.png"))); // NOI18N
        accountButton.setText("Account");
        accountButton.setFocusable(false);
        accountButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        accountButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(accountButton);
        jToolBar1.add(jSeparator4);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/Button-Close-icon-16.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tplMainBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, 510, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/merlin_176507883_99c30ad7-2cc1-4071-8cc2-52866fb7b05c-articleLarge.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jSeparator6))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );

        jToolBar1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exploreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exploreButtonActionPerformed
        if(mExplorePanel==null){
            mExplorePanel = new ExplorePanel();
            ImageIcon icon = new ImageIcon(getClass()
                    .getResource("/com/mycompany/moviemanagementsystem/icon/open-file-icon-16.png"));
            tplMainBoard.addTab("Explore", icon, mExplorePanel, "Explore");
        }
        tplMainBoard.setSelectedComponent(mExplorePanel);
        
    }//GEN-LAST:event_exploreButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if(mSearchPanel == null){
            mSearchPanel = new SearchPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/search-icon-24.png"));
            tplMainBoard.addTab("Search", icon, mSearchPanel, "Search");}
        tplMainBoard.setSelectedComponent(mSearchPanel);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        if(mAccountPanel == null){
            mAccountPanel = new AccountPanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/Person-Male-Light-icon-24.png"));
            tplMainBoard.addTab("Account", icon, mAccountPanel, "Account");}
        tplMainBoard.setSelectedComponent(mAccountPanel);
        Timer stopwatch;
        int count = 0;
        int delay = 1000;
    }//GEN-LAST:event_accountButtonActionPerformed

    private void genresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genresButtonActionPerformed
        if(mGenrePanel == null){
            mGenrePanel = new GenrePanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/trendy.png"));
            tplMainBoard.addTab("Genres", icon, mGenrePanel, "Genres");}
        tplMainBoard.setSelectedComponent(mGenrePanel);
    }//GEN-LAST:event_genresButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int response = JOptionPane.showConfirmDialog(rootPane,"Do you really want to exit ?");
    if(response == JOptionPane.YES_OPTION){
        System.exit(0);
    }
    if(response == JOptionPane.NO_OPTION ){
        System.out.println("Ok");
    }
    if(response == JOptionPane.CANCEL_OPTION){
        System.out.println("Abort exit");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JButton exploreButton;
    private javax.swing.JButton genresButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
}
