/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.moviemanagementsystem.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author haicd
 */

public class SearchPanel extends javax.swing.JPanel {
    String url = "jdbc:mysql://localhost/ktpm3";
    String userName = "root";
    String password = "";
    int row;
    
    DefaultListModel defautListModel = new DefaultListModel();
    String searchText;
    JPanel frame1;
    static JTable table;
    String[] columnNames = {"Movie "};
    String from;
    DefaultTableModel model;
    public SearchPanel() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        searchArea = new javax.swing.JTextField();
        searchButtonSearchPanel = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Movie name"
            }
        ));
        jScrollPane1.setViewportView(searchTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 66, 390, 180));

        searchArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAreaActionPerformed(evt);
            }
        });
        add(searchArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 31, 230, -1));

        searchButtonSearchPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/moviemanagementsystem/icon/search-icon-16.png"))); // NOI18N
        searchButtonSearchPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonSearchPanelActionPerformed(evt);
            }
        });
        add(searchButtonSearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 40, 22));

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 22));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/white-background-with-blue-tech-hexagon_1017-19366.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonSearchPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonSearchPanelActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            searchText = searchArea.getText();
            Connection connect =DriverManager.getConnection(url, userName, password);
            String searchQuery = "select Name from movies where Name like '" + searchText + "%'";
            PreparedStatement pst = connect.prepareStatement(searchQuery);
            ResultSet rsSearch = pst.executeQuery();
            searchTable.setModel(DbUtils.resultSetToTableModel(rsSearch));
            
        } catch (Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_searchButtonSearchPanelActionPerformed

    private void searchAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAreaActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
         row = searchTable.getSelectedRow();
        String id = (searchTable.getModel().getValueAt(row,0).toString());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/ktpm3";
            String userName = "root";
            String password = "";
            Connection connected =DriverManager.getConnection(url, userName, password);
            String sql = "UPDATE movies SET Views = Views + 1 WHERE Name = '"+id+"'";
            PreparedStatement pstmt = connected.prepareStatement(sql);
            pstmt.executeUpdate();
            pstmt.close();
           
        } catch (Exception e){
            e.printStackTrace();
        }
        MovieInformationFrame du = new MovieInformationFrame(id);
        du.loadInformation(id);
        du.setVisible(true);
        du.setDefaultCloseOperation(du.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_viewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchArea;
    private javax.swing.JButton searchButtonSearchPanel;
    private javax.swing.JTable searchTable;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
